### ISSUE TITLE
May i ask your a question about rotation problem in VR?

### ISSUE THREAD

**Issue by carvinchen** [DanWuh/Motive2Unity#1]
Hi, DanWuh

Sorry, my question is not really to your programm, just i think maybe your have better solution about my problem. If you dont like my question, just delete it.

I am using Optitrack Motive to track the markers that i weared on my finger and using Unity to create 3d objects.

And middleVR (free edition) for 3d classes.

If i move my finger, i will see the 3d object for finger move with my finger too. It works.
But if i sometimes rotate my finger 90 degrees or 180 degrees, the 3d finger object will jump to the opposite site and rotates 180 degrees back...

And as your know, i am using the code written by MattOscamp (https://github.com/MattOskamp/UnityOptitrack/tree/master/Assets/Scripts)

Video for problem:
http://de.tinypic.com/player.php?v=dqmxiu&s=8#.Vhf0Xvntmko

Have your any idea about my problem? 

Thank your!

regards,

Carvin

**Comment by DanWuh** [comment]
Hey Carvin,

Right now it sounds like your rigid body is flipping, I would start there before attempting to debug any code.

Double check the marker layout on your hands as well as the rigid body performance in motive. As a rule of thumb, it's worth trying to add a couple more markers to flesh out the rigid bodies.

By all means shoot me an image of your existing marker layout, I may have some ideas.

Cheers

Oh one last thing. I recall that motive switched orientation recently so it's possible that Katy's code is flipping y and q and you may not need that any more.

**Comment by carvinchen** [comment]
Good morning, DanWuh 

Thank you for your answer! 
1. If only rigid body is flipping, i could also freeze the Rotation on the Rigid body component, i tried it, but it doesnt work ...
2. Each marker has 3 reflections sphere for tracking, these 3 points -> surface has x, y, z coordinate. 
   I checked it's performance in Motive before and it is correct, i think.
3. If you have seen my link  http://de.tinypic.com/player.php?v=dqmxiu&s=8#.Vhf0Xvntmko  
   You may have some more idea? 
4. Have you the same problem with your own Code Motive2Unity ?
5. I have modified his Code( offset for position and -euler.x | -euler.y for right rotation ) for my project, because Motive and Unity have different axis.

Have you any idea? 

Thank you.

regards.

**Comment by DanWuh** [comment]
Hey Carvin,

My understanding was that Unity uses Quaternions as preference and you have
to convert those Motive Euler angles through the code. Hence why the
Optitrack samples all have those Quaternion conversion samples.

A good example of usages is in this Unity link;
http://answers.unity3d.com/questions/765683/when-to-use-quaternion-vs-euler-angles.html

I totally agree that its not likely your markers, I thought you may have
been using an Optitrack standard hand marker set (like I had) but the glove
with raised markers is a genius idea. Great work!

So as long as the rigid body appears to track correctly in Motive, the
obvious issue is down to how the Quaternions are interpreting the Euler
code.

You could try converting your eulers back to Quaternions during evaluation,
EG:

for(int index=0; index<boneList.Count; index++)
{
int id = System.Convert.ToInt32(boneList[index].Attributes["ID"].InnerText);
float x = (float)
System.Convert.ToDouble(boneList[index].Attributes["x"].InnerText);
float y = (float)
System.Convert.ToDouble(boneList[index].Attributes["y"].InnerText);
float z = (float)
System.Convert.ToDouble(boneList[index].Attributes["z"].InnerText);
float qx = (float)
System.Convert.ToDouble(boneList[index].Attributes["qx"].InnerText);
float qy = (float)
System.Convert.ToDouble(boneList[index].Attributes["qy"].InnerText);
float qz = (float)
System.Convert.ToDouble(boneList[index].Attributes["qz"].InnerText);
float qw = (float)
System.Convert.ToDouble(boneList[index].Attributes["qw"].InnerText);
- //== coordinate system conversion (right to left handed) ==--*
- z = -z;*
- qz = -qz;*
- qw = -qw;*
  //== bone pose ==--
  Vector3    position    = new Vector3(x,y,z);
  Quaternion orientation = new Quaternion(qx,qy,qz,qw);

This is extracted directly from the Optitrack unity plugin sample in
natnet. In their code, they set up the euler AND a quaternion equivalent
with a Z offset on both coord systems as well as reversing the Quaternion
"aim".  My god I hate rotation math.

WIthout direct hands on, its pretty hard for me to come up with any
concrete solutions without having the system to hand but I think taking a
look over the rotation math you are using is the key.  If im honest, the
flip you are seeing is classic Euler flipping which leads me to think you
should convert back to quaternion.

I hope that helps!
Dan

**Comment by carvinchen** [comment]
May i have your email adress? Thank your!

**Comment by carvinchen** [comment]
Do your know if it is possible to read the position of an optitrack marker (only one sphere) from Motive to Unity? Thank you!
